
spring:
  application:
    name: hello-spring-cloud-config-client
  cloud:
    config:
      uri: http://localhost:8888
      name: configclient
      label: master
      profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/