spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Liaoun/could-config.git
          search-paths: respo
          username: 2900798493@qq.com
          password: lkl1124...

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
